package com.zui.zuicontrol

object ZuiControlContract {
    const val CMD_APPLY_ZUIPP = "apply_zuipp"
    const val CMD_RESTORE_ZUIPP = "restore_zuipp"
    const val CMD_RESTORE_LAST_GOOD = "restore_last_good"
    const val CMD_RESTORE_OFFICIAL_ORIGINAL = "restore_official_original"
    const val CMD_STATUS = "status"
    const val CMD_SET_PERFORMANCE_PROFILE = "set_performance_profile"
    const val CMD_SET_PERFORMANCE_PROFILE_STAGED = "set_performance_profile_staged"
    const val CMD_REMOVE_PERFORMANCE_PROFILE = "remove_performance_profile"
    const val CMD_APPLY_PERFORMANCE = "apply_performance"
    const val CMD_SYNC_XML_REFRESH = "sync_xml_refresh"
    const val CMD_EXPORT_LOGS = "export_logs"

    const val KEY_REQUEST_TEXT = "zui_control_request_text"
    const val KEY_STATUS_TIME = "zui_control_status_time"
    const val KEY_STATUS_LAST = "zui_control_status_last"
    const val KEY_STATUS_TEXT = "zui_control_status_text"
    const val KEY_DAEMON_STATUS_TEXT = "zui_control_daemon_status_text"
    const val KEY_DAEMON_REFRESH_STATE = "zui_control_daemon_refresh_state"
    const val KEY_PERFORMANCE_PROFILES_TEXT = "zui_control_performance_profiles_text"
    const val KEY_PERFORMANCE_SUMMARY = "zui_control_performance_summary"
    const val KEY_TOP_PACKAGE = "zui_control_top_package"
    const val KEY_ACTIVE_REFRESH = "zui_control_active_refresh"
    const val KEY_SCENE_EVENT_TEXT = "zui_control_scene_event_text"
    const val KEY_ZUIPP_RELOAD_STATE = "zui_control_zuipp_reload_state"
    const val KEY_PP_MODE_STATE = "zui_control_pp_mode_state"
    const val KEY_ASOUL_HEALTH = "zui_control_asoul_health"
    const val KEY_XML_STATE = "zui_control_xml_state"
    const val KEY_LOG_EXPORT = "zui_control_log_export"

    const val ACTION_APPLY_PP_MODE = "com.zui.zuicontrol.action.APPLY_PP_MODE"
    const val ACTION_REFRESH_NOTIFICATION = "com.zui.zuicontrol.action.REFRESH_NOTIFICATION"
    const val ACTION_SET_60 = "com.zui.zuicontrol.action.SET_60"
    const val ACTION_SET_90 = "com.zui.zuicontrol.action.SET_90"
    const val ACTION_SET_120 = "com.zui.zuicontrol.action.SET_120"
    const val ACTION_SET_144 = "com.zui.zuicontrol.action.SET_144"
    const val ACTION_SET_165 = "com.zui.zuicontrol.action.SET_165"
    const val EXTRA_RATE = "rate"
    const val EXTRA_PACKAGE = "package"
    const val EXTRA_PP_MODE = "pp_mode"

    val rates = listOf(60, 90, 120, 144, 165)
}
